/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_passerbywhu_jnistudy_MainActivity */

#ifndef _Included_com_passerbywhu_jnistudy_MainActivity
#define _Included_com_passerbywhu_jnistudy_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_passerbywhu_jnistudy_MainActivity
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_passerbywhu_jnistudy_MainActivity_getText
  (JNIEnv *, jobject);

/*
 * Class:     com_passerbywhu_jnistudy_MainActivity
 * Method:    show
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_passerbywhu_jnistudy_MainActivity_show
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
